config/routes.rb
Ideabakery2::Application.routes.draw do

  

  

  devise_for :users

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "signup", :to => "devise/registrations#new"
    get "settings", :to => "devise/registrations#edit"
  end

  get "users/index"

  resources :ideas do
    resources :pictures
    resources :updates
  end

  resources :users

  root :to => 'static#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base


  belongs_to :users
  has_many :updates, :dependent => :destroy
  has_many :pictures, :dependent => :destroy

  attr_accessible :desc, :featured, :progress, :title, :tag_list, :pictures_attributes, :pictures

  accepts_nested_attributes_for :pictures, :allow_destroy => true, :reject_if => lambda { |a| a[:filepicker_url].blank? }


  acts_as_taggable

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        create_pictures

        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        create_pictures
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def create_pictures
    params[:pictures][:filepicker_url].each do |filepicker_url|
      if ((filepicker_url.present?) && (filepicker_url != "[]"))
        filepicker_url_splitted = filepicker_url.split(",") #If creator do multi upload, then the filepicker are like this :["https://www.filepicker.io/api/file/g238Ev8xRl2I9KogOHix,https://www.filepicker.io/api/file/0kNeqcS2TZWbRDIU5yL6,https://www.filepicker.io/api/file/eDlmuXCTxGV1L7jRIJsA"] . We split it to make differents creation_galleries
        filepicker_url_splitted.each do |filepicker_url_splitted|
          @idea.pictures.create(:filepicker_url => filepicker_url_splitted)
        end
      end
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for @idea, html: {multipart: true} do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="col-lg-12">
  <%= f.input :title  %>
  <%= f.input :desc %>
  <%= f.input :progress, collection: 1..5 %>
  <%= f.input :tag_list %> 
  <%= f.filepicker_field :pictures, dragdrop: true, store_location: "S3", name: "pictures[filepicker_url][]", multiple: "true", mimetypes: "image/gif,image/jpeg,image/pjpeg,image/png,image/svg+xml,image/tiff" %>
  <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<h1>Listing ideas</h1>

<%= stylesheet_link_tag "ideas.css" %>
 <link href="dist/css/ideas.css" rel="stylesheet">
<table id="ideas" class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Featured</th>
    <th>Progress</th>
    <th>Pictures</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.title %></td>
    <td><%= idea.desc %></td>
    <td><%= idea.featured %></td>
    <td><%= idea.progress %></td>
    <td><%= idea.pictures.count %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
        <div class="row" style="padding:50px;0px;100px;25px">
            <h1 style="padding-left:450px;0px;0px;-100px">New Idea </h1>
            
          </div>
        </div><!-- /.row -->

        <div class="row">
          

            <form role="form">

              <div class="form-group">
                <label>Title</label>
                <input class="form-control">
            
             
              </div>


              <div class="form-group">
                <label>Description</label>
                <textarea class="form-control" rows="15"></textarea>
              </div>

              <div class="form-group">
                <label>File input</label>
                <input type="file">
              </div>


              <button type="submit" class="btn btn-default">Create Idea</button>
              <button type="reset" class="btn btn-default" >Reset Button</button>  

            </form>

		</div>

<!-- <div class="row">
<h1 class= >New Idea</h1>

<%= render 'form' %>

 <%= link_to 'Back', ideas_path %>
 -->

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<!--carousel image slider-->

<div class="container">
<div class="row">
<div class="box">
<div class="col-lg-12 text-center"><!-- find col class for appropriate design-->

	<div id="carousel-example-generic" class="carousel slide">
              <!-- Indicators -->
              <ol class="carousel-indicators hidden-xs">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              </ol>
            
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <%= image_tag('slide-1.jpg')%>
                 	 <div class="container">
	            		<div class="carousel-caption">
	              		<h1>Example headline.</h1>
                		</div>
                	</div>
                </div>
                <div class="item">
                  <%= image_tag('slide-2.jpg')%>
                </div>
                <div class="item">
                  <%= image_tag('slide-3.jpg')%>
                </div>
              </div>
            
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="icon-prev"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="icon-next"></span>
              </a>
          </div>
</div>
</div>
</div>
<!--end image slider-->

<!--side bar for project profile here-->

<p>
  <b>Title:</b>
  <%= @idea.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @idea.desc %>
</p>

<p>
  <b>Featured:</b>
  <%= @idea.featured %>
</p>

<p>
  <b>Progress:</b>
  <%= @idea.progress %>
</p>

<% @idea.pictures.each do |picture| %>
	<%= filepicker_image_tag picture.filepicker_url, w: 436, fit: 'clip' %>

<% end %>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>