config/routes.rb
Ideabakery2::Application.routes.draw do

  

  

  devise_for :users

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "signup", :to => "devise/registrations#new"
    get "settings", :to => "devise/registrations#edit"
  end

  get "users/index"

  resources :ideas do
    resources :pictures
    resources :updates
  end

  resources :users

  root :to => 'static#index'

end

app/models/update.rb
class Update < ActiveRecord::Base
  attr_accessible :title, :desc
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updates }
    end
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = Update.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/new
  # GET /updates/new.json
  def new
    @update = Update.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/1/edit
  def edit
    @update = Update.find(params[:id])
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(params[:update])

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render json: @update, status: :created, location: @update }
      else
        format.html { render action: "new" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /updates/1
  # PUT /updates/1.json
  def update
    @update = Update.find(params[:id])

    respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to updates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>Listing updates</h1>

<table>
  <tr>
    <th>Desc</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @updates.each do |update| %>
  <tr>
    <td><%= update.desc %></td>
    <td><%= update.desc %></td>
    <td><%= link_to 'Show', update %></td>
    <td><%= link_to 'Edit', edit_update_path(update) %></td>
    <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @update.desc %>
</p>

<p>
  <b>Desc:</b>
  <%= @update.desc %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>